# Generated by Django 2.1.15 on 2020-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('homeworld', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=50)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
