# Generated by Django 2.1.15 on 2020-10-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20201015_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='puntaje',
            new_name='rating',
        ),
    ]
